Contract
NOOBDY/OutOfMoneyError pull request #3
Opened 2024-05-15 19:55 UTC by OuChiaYun

檔案在 test.sol
試寫，然後應該沒有任何的防呆(警告)

er.png 供參，但他挺錯的，有時間我會畫一張對的

2024-05-16 08:11 UTC, NOOBDY requested changes
is there any testing function i can use or is there any way i could test it?

2024-05-16 08:11 UTC, NOOBDY commented on packages/contracts/package-lock.json
this shouldn't be here

2024-05-16 08:11 UTC, NOOBDY commented on packages/contracts/package.json
does this affect anything?

2024-05-18 12:50 UTC, OuChiaYun commented on packages/contracts/package-lock.json
delete

2024-05-18 12:51 UTC, OuChiaYun commented on packages/contracts/package.json
no,
我只是以為他跟lock一樣是多出來的

2024-05-24 08:03 UTC, NOOBDY approved these changes

2024-05-24 08:04 UTC, merged